<?php
$title = 'Add Admin User';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('manager', array('action' => 'adduser')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<table>
<tr>
<td style="padding-left:15px;">
<b><?php echo $title?></b>
</td>
</tr>
</table>
<table align="center" width="50%"  class="adminadduser"> 
	<tr>
	<td >
	<?php 
	if(count($this->flashMessages)) : ?>
    <?php foreach ($this->flashMessages as $msg) : ?>
	  <p align="center">  <?php echo $msg; ?></p>
    <?php endforeach; ?>
	<?php endif; ?>
	</td>
	</tr>
	
	<tr>
		<td><?php echo $this->formlabel($form->get('firstname'));?>:</td>
		<td><?php echo $this->forminput($form->get('firstname'));?></td>
	</tr>
	
	
	<tr>
		<td><?php echo $this->formlabel($form->get('lastname'));?>:</td>
		<td><?php echo $this->forminput($form->get('lastname'));?></td>
	</tr>
	
	<tr>
		<td><?php echo $this->formlabel($form->get('email'));?>:</td>
		<td><?php echo $this->forminput($form->get('email'));?>
		<ul class="error_list">
<li id="emailMgs"></li>
		</td>
	</tr>
	
	
	<tr>
		<td><?php echo $this->formlabel($form->get('username'));?>:</td>
		<td><?php echo $this->forminput($form->get('username'));?></td>
	</tr>
	<tr>
		<td><?php echo $this->formlabel($form->get('password'));?>:</td>
		<td><?php echo $this->forminput($form->get('password'));?></td>
	</tr>
	
	<tr>
		<td><?php echo $this->formlabel($form->get('status'));?></td>
		<td><?php echo $this->formRow($form->get('status'));?></td>
	</tr>
	
	
	<tr>
		<td>
		</td>
		<td><?php echo $this->formSubmit($form->get('submit')); ?></td>
	</tr>
</table>

<?php 

echo $this->form()->closeTag();
?>
<script language="javascript">

function checkEmail(email){
    var email = $('#email').val();
    
    var reg = /^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/;
    if (reg.test(email)){
    	$('#emailMgs').html(" ");
    return true; 
   }
    else{
    	$('#emailMgs').html("Please provide a valid email");    	
		$('#email').val('');
    return false;
    } 

}


</script>