
<script>
$(document).ready(function() {
	CKEDITOR.replace( 'templateBodyArea', {
		uiColor: '#14B8C4',
		toolbar: [
		{ name: 'document', items: [ 'Source', '-', 'NewPage', 'Preview', '-', 'Templates' ] },
		[ 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo' ],

		{ name: 'editing', groups: [ 'find', 'selection', 'spellchecker' ],
		items: [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
		{ name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
		{ name: 'others', items: [ ' ' ] },
		{ name: 'about', items: [ 'About' ] },
		[ 'Bold', 'Italic', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink' ],
		[ 'TextColor', 'BGColor' ],

		{ name: 'paragraph',
		groups: ['indent', 'blocks', 'align', 'bidi' ],
		items: ['-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl' ] },
		{ name: 'insert', items: [ 'Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak'] },

		{ name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },

		],
		resize_enabled : false,
		width: "700px",
		height: "200px"
	});
});

function insertElements(insertValue)
{
       CKEDITOR.instances['templateBodyArea'].insertText(insertValue);
}

</script>
<?php
if (isset($flashMessage) && !empty($flashMessage)) {
    ?>
<div id="flashMessageDiv" class="green_highlight">
	<?php
    foreach ($flashMessage as $message) {
        ?>
	<p><?php echo $message;?></p>
	<?php
    }
    ?>
	</div>
<?php
}
?>

<?php
$form = $this->editTemplate;
$form->setAttribute('action', 
    $this->url('manager', array('action' => 'updateTemplate')));
$form->setAttribute('method', 'post');
$form->setAttribute('id', 'frm');
$form->setAttribute('name', 'frm');
$form->setAttribute('class', 'dlForm multiForm');
// $form->setAttribute('onsubmit', 'return formValidate()');
$form->prepare();
echo $this->form()->openTag($form);

?>
<table>
	<tr>
		<td>
	           <?php
            $id = $form->get('id');
            echo $this->formhidden($id)?>
	         </td>
	</tr>
	<tr>
		<td>
			<table>
				<tr>
					<td>
	                    	<?php
                    $templateName = $form->get('templateName');
                    echo $this->formLabel()->openTag($templateName) .
                         $templateName->getLabel();
                    ?>
							<?php
    
    $this->formLabel()->closeTag();
    ?>
						</td>
					<td>
							<?php echo $this->formtext($templateName)?>
						</td>
					<td>
						<div id="errorMsg" style="display: none;"></div>
					</td>
				</tr>
				<tr>
					<td>    
			            	<?php
                $templateSubject = $form->get('templateSubject');
                echo $this->formLabel()->openTag($templateSubject) .
                     $templateSubject->getLabel();
                ?>
							<?php
    
    $this->formLabel()->closeTag();
    ?>
						</td>
					<td>
			            	<?php echo $this->formtext($templateSubject)?>
			            </td>
				</tr>
				<tr>
			
			</table>
			<table width="100%">
				<td>
			            	<?php echo $this->formtextarea($form->get ( 'templateBody' ))?>
			            </td>
				<td>
					<div style="background-color: #14B8C4;">
						<ul type="none">
							<li><a href="javascript:void()"
								onclick="javascript:insertElements('#userName#')">User Name</a></li>
							<br />
							<li><a href="javascript:void()"
								onclick="javascript:insertElements('#email#')">Email</a></li>
							<br />
							<li><a href="javascript:void()"
								onclick="javascript:insertElements('#password#')">Password</a></li>
							<br />
							<li><a href="javascript:void()"
								onclick="javascript:insertElements('#url#')">URL</a></li>
						</ul>
					</div>
				</td>
				</tr>
			</table>
		</td>
	</tr>
	<tr>
		<td colspan="2">
	         	<?php echo $this->formSubmit($form->get('submit')); ?>
	         </td>
	</tr>
</table>
<?php echo $this->form()->closeTag();?>

