<?php
$title = 'Admin Manager Login';
$this->headTitle($title);
$form = $this->form;
$form->setAttribute('action', $this->url('manager', array('action' => 'index')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
?>
<table align="center" width="50%"  class="adminlogin"> 
	<tr>
	<td colspan="2">
	<?php 
	if(isset($flashMessage) && !empty($flashMessage)) 
	{
	?>
    	<?php 
    	foreach ($flashMessage as $msg)
    	{
    	?>
	  <div><?php echo $msg; ?></div>
    	<?php  
    	}
    	?>
	<?php 
	}
	?>
	</td>
	</tr>
	<tr>
		<td><?php echo $this->formlabel($form->get('username'));?></td>
		<td><?php echo $this->forminput($form->get('username'));?></td>
	</tr>
	<tr>
		<td><?php echo $this->formlabel($form->get('password'));?></td>
		<td><?php echo $this->forminput($form->get('password'));?></td>
	</tr>
	<tr>
		
		<td></td>
		<td>
		<?php echo $this->formSubmit($form->get('submit')); ?> &nbsp;<?php echo $this->formReset($form->get('cancel')); ?>
		</td>
	</tr>
</table>

<?php 

echo $this->form()->closeTag();
?>