<div class="clear"></div>
<div class="footer">
  <div class="footer_wrapper">
    <div class="copyright">Copyright © 2011 Passport Services LLC. All rights reserved.</div>
    <div class="footer_links">
      <ul>
        <li><a href="<?php //echo $this->url('privacy') ?>"><?php echo $this->translate('Privacy Policy') ?></a></li>
        <li><a href="<?php //echo $this->url('term') ?>"><?php echo $this->translate('Terms of Use') ?></a></li>
        <li><a href="<?php //echo $this->url('contactus') ?>"><?php echo $this->translate('Contact Us') ?></a></li>
      </ul>
    </div>
  </div>
</div>
