<?php
use Zend\Session\Container;
?>

  <head>
    <meta charset="utf-8">
    

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- stylessheet  -->
   <?php echo $this->headTitle($this->translate('Passport Services LLC'))->setSeparator(' - ')->setAutoEscape(false) ?>
        

        <!-- styles sheet -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/global.css')	
                        //->prependStylesheet($this->basePath() . '/css/ie6.css', array('conditional' => 'lt IE 6',))
                        //->prependStylesheet($this->basePath() . '/css/ie6style.css', array('conditional' => 'lt IE 6',))
         ?>

        <!-- Js Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery-1.js')
            ->prependFile($this->basePath() . '/js/general.js');
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
         ?>
   </head>
	
	<div>
	
	<div>
	<?php
		echo $this->render('/customlayout/header'); 
		?>
		</div>
		
	<div   width="10%" class="active" style="vertical-align:text-top; border-color:#000; float:left; ">
	<?php  echo $this->render('/customlayout/left');  ?>
	</div>	
	<div style="height:500px;">
	<?php echo $this->content;?>
	</div>
	
	<div>
	<?php echo $this->partial('customlayout/footer'); ?>
	</div>
		
   </div>
   
   
   
   
   
   
   
   
   
   
   
   

