<?php
use Zend\Session\Container;
?>  <html>
	<head>
    <meta charset="utf-8">
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- stylessheet  -->
   <?php echo $this->headTitle($this->translate('Passport Services LLC'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <!-- styles sheet -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/global.css')	
         ?>
        <!-- Js Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/ckeditor/adapters/jquery.js')
            ->prependFile($this->basePath() . '/js/ckeditor/ckeditor.js');
         ?>
   </head>
	<body>
	<div>
	
	<div>
	<?php
		echo $this->render('/customlayout/header'); 
		?>
		</div>
			
	<div width="25%" class="active" style="vertical-align:text-top; border-color:#000; float:left;">
	<?php  echo $this->render('/customlayout/left');  ?>
	</div>	
	<div style="height:500px;">
	<?php echo $this->content;?>
	</div>
	
	<div>
	<?php echo $this->partial('customlayout/footer'); ?>
	</div>
		
   </div>
   </body>
   </html>
   
   
   
   
   
   
   
   
   
   
   
   

