<?php 
use Zend\Session\Container;
echo $this->doctype();
$container = new Container('namespace');
$data= $container->adminsession;
if($data)
{
?>
<table width="100%" style="border-color:#6495ED;border-style:solid; border-width:1px;  height:505px;">
<tr>
<td class="active">Admin Management
<p><a href="<?php echo $this->url('manager',array('action'=>'adduser')) ?>">Add User</a></p>
<p><a href="<?php echo $this->url('manager',array('action'=>'userlist')) ?>">Admin User List</a></p>
</td>
</tr>
<tr>
<td class="active">CMS Management
<p><a href="<?php echo $this->url('manager',array('action'=>'contact')) ?>">Contact User</a></p>
<p><a href="<?php echo $this->url('manager',array('action'=>'feedback')) ?>">Feedback User</a></p>
</td>
 
 
</tr>
<tr>
<td  >User management
<p><a href="<?php echo $this->url('manager',array('action'=>'register')) ?>">Register User</a></p>

</td>
</tr>
<tr>
<td  >Template
<p><a href="<?php echo $this->url('manager',array('action'=>'templates')) ?>">List Templates</a></p>
<p><a href="<?php echo $this->url('manager',array('action'=>'addtemplate')) ?>">Add Template</a></p>
<p><a href="<?php echo $this->url('manager',array('action'=>'templateMail')) ?>">Add Template</a></p>
</td>
</tr>

<tr>
<td class="active">
	<a href="<?php echo $this->url('manager',array('action'=>'logout')) ?>">Logout</a>
</td>
</tr>
<?php
}
?>		
</table>

