<div class="clear"></div>
<div class="wrapper">
  <div class="banner"><img alt="Passport Services" src="<?php $this->basepath('public')?>/images/feedback_banner.gif"></div>
  <div class="clear"></div>
  <div class="container_main">
    <div class="new_container">
      <!--Heading Container Section Starts Here-->
      <div class="heading_container">
        <div class="heading_container_left"></div>
        <div class="heading_containerbg">
          <div class="page_heading">Feedback</div>
        </div>
        <div class="heading_container_right"></div>
      </div>
      <!--Heading Container Section Ends Here-->
      <!--Form Inner/Inside Section Starts Here-->
      <div class="form_inside_section">
        <div class="bodyContent">
          <div class="body_text">
          <?php
            if(isset($flashMessage) && !empty($flashMessage))
            {
            ?>
            <div class="green_highlight" id = "msgDiv">
            <?php 
            	foreach($flashMessage as $val)
            	{
            ?>
            	<p><?php echo $val?></p>
            <?php 
            	}
            	//$flashMessage = NULL;
            ?>
            </div>
            <?php 
            }
          ?>
            <div class="clear"></div>
            <p> We thank you for visiting </p>
            <p>Your feedback helps us to improve the quality of services. We look forward to your contribution in making Passport Services LLC a solution that can serve you better.</p>
            <p><strong>Kindly fill up the Feedback form below.</strong></p>
            <p>
            </p><div class="bodyContent">
            
            <?php
				$form = $this->feedback;
				$form->setAttribute ( 'action', $this->url( 'communicate', array ('action' => 'saveFeedback')));
				$form->setAttribute ( 'method', 'post' );
				$form->setAttribute ( 'id', 'frm');
				$form->setAttribute ( 'name', 'frm');
				$form->setAttribute ( 'class', 'dlForm multiForm');
			  	//$form->setAttribute('onsubmit', 'return formValidate()');
				$form->prepare ();
				echo $this->form ()->openTag ( $form );
			?>
			<div>
                  <!--Fieldset Section Starts Here-->
                  <fieldset class="bdr">
			        <dl>
	                    <dt><?php
							$name = $form->get ( 'txt_name' );
							echo $this->formLabel()->openTag($name) . $name->getLabel();
							?>
							<span class="red">*</span>
							<?php $this->formLabel()->closeTag();
							?>
						</dt>
	                    <dd>
			            	<?php echo $this->formText($name) ?>
			            <div id="txt_name_error" class="red"></div>
			            </dd>
	                </dl>
					<dl>
	                    <dt><?php
							$email = $form->get ( 'txt_email' );
							echo $this->formLabel()->openTag($email) . $email->getLabel();
							?>
							<span class="red">*</span>
							<?php $this->formLabel()->closeTag();
							?>		
						</dt>
	                   	<dd>
	                   		<?php echo $this->formtext($email)?>
						<div id="txt_email_error" class="red"></div>
						</dd>
	                  </dl>
					<dl>
	                    <dt><?php
							$phone = $form->get ( 'txt_phone' );
							echo $this->formLabel()->openTag($phone) . $phone->getLabel();
							?>
							<span class="red">*</span>
							<?php $this->formLabel()->closeTag();
							?>
						</dt>
	                    <dd id="db_width">
	                    <div class="lblField">
	                    	<?php echo $this->formtext($phone)?>
						<div id="txt_phone_error" class="red"></div>
						</div>
						</dd>
	                  </dl>
	                  <dl>
	                    <dt><?php
							$enquiry = $form->get ( 'txt_enquiry' );
							echo $this->formLabel()->openTag($enquiry) . $enquiry->getLabel();
							?>
							<span class="red">*</span>
							<?php $this->formLabel()->closeTag();
							?>
						</dt>
	                    <dd>
	                    	<?php echo $this->formtextarea($enquiry); ?>
						<div id="txt_enquiry_error" class="red"></div>
						</dd>
	                  </dl>
				</fieldset>
				 <!--Fieldset Section Ends Here-->
                 <!--Button Section Starts Here-->
                <div class="pixbr XY20">
                    <center id="multiFormNav">
                      <div align="center">
                        <table align="center" class="nobrd">
						<tr>
							<td align="center"><div class="lblButton">
							<?php echo $this->formSubmit($form->get('submit')); ?>
							</div>
                                <div class="lblButtonRight">
                                  <div class="btnRtCorner"></div>
                            </div>
							</td>
							<td align="center"><div class="lblButton">
							<?php echo $this->formReset($form->get('cancel')); ?>
							</div>
                                <div class="lblButtonRight">
                                  <div class="btnRtCorner"></div>
                                </div>
							</td>
						</tr>
						</table>
						</div>
                    </center>
                  </div>
                  </div>
		        <?php echo $this->form()->closeTag()?>
                  <!--Button Section Ends Here-->
            </div>
			<p>We value your opinion and hope to serve you better.</p>
            <p></p>
          </div>
        </div>
      </div>
      <!--Form Inner/Inside Section Ends Here-->
    </div>
    <div class="container_bottombg"></div>
  </div>
</div>
<script>
$('#frm').submit(function()
{
	var errFlag = false;
	if(trim($('#txt_name').val()) == '')
	{
		$('#txt_name_error').html('Please enter your name.');
	    $('#txt_name').focus();
	    errFlag = true;
	}
	
	if(trim($('#txt_email').val()) == '')
	{
	    $('#txt_email_error').html('Please enter your email address.');
	    errFlag = true;
	}
	else if(validateEmail($('#txt_email').val()) != 0)
	{
	    $('#txt_email_error').html("Please enter valid email address.");
	    errFlag = true;
	}
	   
	if(trim($('#txt_phone').val()) == '')
	{
	    $('#txt_phone_error').html('Please enter your phone.');
	    errFlag = true;
	}
	
	if(trim($('#txt_enquiry').val()) == '')
	{
		$('#txt_enquiry_error').html('Please enter your enquiry.');
	    errFlag = true;
	}
	
	if(errFlag)
	{
		return false;
	}
	else
	{
		return true;
	}
});

$(document).ready(function(){
	$(".flushMe").val('');
});

</script><div class="clear"></div>