<?php 
$form = $this->changePasswordForm;
$form->setAttribute ( 'action', $this->url('changePassword'));
$form->setAttribute ( 'onsubmit', 'return fncSubmit()' );
?>
<div class="clear">&nbsp;</div>
<div class="wrapper">
	<div class="container_main">
		<div class="new_container">
			<!--Heading Container Section Starts Here-->
			<div class="heading_container">
				<div class="heading_container_left"></div>
				<div class="heading_containerbg">
					<div class="page_heading">Change Password</div>
				</div>
				<div class="heading_container_right"></div>
			</div>
			<!--Heading Container Section Ends Here-->
			<!--Form Inner/Inside Section Starts Here-->
			<div class="form_inside_section">

				<div class="bodyContent">
					<div class="body_text">
						<h2><?php echo "user firstname"; ?> ,</h2>

						<h3>Enter your new password in the form below.</h3>
					</div>
					<div class="clear"></div>
                    					<?php
										$form->prepare ();
										
										echo $this->form ()->openTag ( $form );
										echo $this->formHidden($form->get('unique_key'));
											?>
                        <table class="login_form" border="0"
						cellpadding="0" cellspacing="5" align="center">
						<tbody>
							<tr>
								<td></td>
							</tr>
							<tr>
								<th><label for="sf_guard_user_password"><?php echo $this->formLabel($form->get('password')); ?> 
 <span class="red">*</span></label></th>
								<td><?php echo $this->formInput($form->get('password')); ?></td>
							</tr>
							<tr>
								<th><label for="sf_guard_user_password_again"><?php echo $this->formLabel($form->get('confirm_password')); ?><span
										class="red">*</span></label></th>
								<td>
									<ul class="error_list">
										<li id="passwordMgs"></li>
									</ul>
<?php echo $this->formInput($form->get('confirm_password')); ?></td>
							</tr>


							<tr>
								<td>&nbsp;</td>
								<td><input class="btnArea" name="change" value="Change"
									type="submit"></td>
							</tr>
						</tbody>
					</table>
                   <?php echo $this->form ()->closeTag ();	?>
                </div>
			</div>
			<!--Form Inner/Inside Section Ends Here-->
		</div>
		<div class="container_bottombg"></div>
	</div>
</div>
<div class="clear"></div>
<script>

function checkPassword(){
	$('#passwordMgs').fadeIn();
	if( $('#password').val() != $('#confirm_password').val() ) {

			$('#passwordMgs').html("Password doesn't match");
	    	
	    	return false;
			
		}else {
			$('#passwordMgs').html(" ");
			return true;
		}
}

function fncSubmit(){
	if( $('#password').val() != $('#confirm_password').val() ) {
		$('#confirm_password').val('');
		$('#passwordMgs').html("Password doesn't match");
		return false;
	}
}

</script>