<h2></h2>
<h1></h1>
<div class="clear"></div>
<div class="wrapper">
	<div class="container_main">
		<div class="new_container">
			<!--Heading Container Section Starts Here-->
			<div class="heading_container">
				<div class="heading_container_left"></div>
				<div class="heading_containerbg">
					<div class="page_heading">Forgot your password?</div>
				</div>
				<div class="heading_container_right"></div>
			</div>
			<!--Heading Container Section Ends Here-->
			<!--Form Inner/Inside Section Starts Here-->
			<div class="form_inside_section">
				<div class="bodyContent">
					<div class="body_text">
						<p>
							<b> Do not worry, we can help you get back in to your account
								safely! Fill out the form below to request an e-mail with
								information on how to reset your password.</b>
						</p>
					</div>
					<div class="clear"></div>
<?php
$form = $this->forgetPasswordForm;
$form->setAttribute('action', $this->url('forgetPassword'));
$form->prepare();

echo $this->form()->openTag($form);
?>
  <table cellpadding="0" cellspacing="5" border="0" align="center"
						class="login_form">
						<tbody>
							<tr>
								<td></td>
							</tr>
							<tr>
								<th><label for="forgot_password_email_address"><?php echo $this->formLabel($form->get('email')); ?></label></th>
								<td>
									<ul class="error_list">
										<li id="emailMgs"></li>
									</ul>
<?php echo $this->formInput($form->get('email')); ?></td>
							</tr>


							<tr>
								<td>&nbsp;</td>
								<td><?php echo $this->formSubmit($form->get('submit')); ?>
 <input type="button" class="btnArea" name="change" value="Back"
									onclick="javascript:location.href=&#39;login&#39;"></td>
							</tr>
						</tbody>
					</table>
<?php
echo $this->form()->closeTag();

?>
 </div>
			</div>
			<!--Form Inner/Inside Section Ends Here-->
		</div>
		<div class="container_bottombg"></div>
	</div>
</div>
<div class="clear"></div>

<script>

function checkEmail(email){
    var email = $('#email').val();
    
    var reg = /^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})$/;
    if (reg.test(email)){
    	$('#emailMgs').html(" ");
    return true; 
   }
    else{
    	$('#emailMgs').html("Please provide a valid email");    	
		$('#email').val('');
    return false;
    } 

}


</script>