<!-- 
 * Organization: OSSCube
* Added: Ramandeep Singh
* Scope: login page
* Dated: 05-09-2013
*/
 -->
<div class="clear">&nbsp;</div>
<div class="wrapper">
	<div class="container_main">
		<div class="new_container">
			<!--Heading Container Section Starts Here-->
			<div class="heading_container">
				<div class="heading_container_left"></div>
				<div class="heading_containerbg">
					<div class="page_heading">Login</div>
				</div>
				<div class="heading_container_right"></div>
			</div>
			<!--Heading Container Section Ends Here-->

			<!--Form Inner/Inside Section Starts Here-->
			<div class="form_inside_section">
				<div class="bodyContent"> 


<?php
$form = $this->loginForm;
$form->setAttribute('action', $this->url('login'));
$form->prepare();

echo $this->form()->openTag($form);

?>

  <table cellpadding="0" cellspacing="5" border="0" width="50%"
						align="center" class="login_form">
						<tbody>
							<tr>
								<th><label for="signin_username"><?php echo $this->formLabel($form->get('user_name')); ?></label></th>
								<td>
									<ul class="error_list">
										<li id="userNameMgs">
<?php
if (isset($flashMessage) && !empty($flashMessage)) {
    foreach ($flashMessage as $msg) {
        echo $msg;
    }
}

?>
</li>
									</ul>
  <?php echo $this->formInput($form->get('user_name')); ?></td>
							</tr>
							<tr>
								<ul class="error_list">
									<li></li>
								</ul>
								<th><label for="signin_password"><?php echo $this->formLabel($form->get('password')); ?></label></th>
								<td><?php echo $this->formInput($form->get('password')); ?></td>
							</tr>
						</tbody>
						<tfoot>
							<tr>
								<td></td>
								<td>
   <?php echo $this->formSubmit($form->get('submit')); ?>
    
         
        </td>
							</tr>
							<tr>
								<td></td>
								<td>
									<div>
										<a class="anchor_link"
											href="<?php  echo $this->url('forgetPassword'); ?>">Forgot
											your password?</a>

										<div>
											<a class="anchor_link"
												href="<?php  echo $this->url('register'); ?>">Register Here</a>
										</div>
									</div>
								</td>
							</tr>
						</tfoot>
					</table>

<?php echo $this->form()->closeTag(); ?>
</div>
			</div>
			<!--Form Inner/Inside Section Ends Here-->

		</div>
		<div class="container_bottombg"></div>
	</div>
</div>

<script>

function checkUserName(userName){
	var numaric = userName;
	for(var j=0; j<numaric.length; j++)
		{
		  var alphaa = numaric.charAt(j);
		  var hh = alphaa.charCodeAt(0);
		  //46 (.) 65 (@) 95 (_)
		  if((hh > 45 && hh<58) || (hh > 63 && hh<91) || (hh > 94 && hh<123))
		  {
		  }
		else{
			$('#userNameMgs').html("The username and/or password is invalid.");

			$('#user_name').val('');
			 return false;
		  }
 		}
	$('#userNameMgs').html(" ");
 return true;
}

</script>