<!--<div class="home_body_bg clearfix"> -->
<div class="header">
  <div class="header_top_section">
    <div class="logo"><a href="<?php echo $this->url('home'); ?>"><img alt="Passport Services LLC Logo" src="<?php $this->basepath('public')?>/images/logo_psl.png" border="0"></a><a></a></div><a>
	</a><div class="login_logout_section"><a></a>
	
	
	<?php 
	use Zend\Session\Container;
	
	$container = new Container('user');
	$data= $container->frontidsession;
	if(!$data) {
	?>
	<a href="<?php echo $this->url('login'); ?>">
	<img alt="Login" src="<?php $this->basepath('public')?>/images/login_img.png"></a>
	<?php 
	}else {
	?>
	<a href="<?php echo $this->url('logout'); ?>">
	<img alt="Logout" src="<?php $this->basepath('public')?>/images/logout_img.png"></a>
	<?php }?>
	
    </div>
  </div>
</div>
<div class="clear">
    
</div><div class="top_nav_section">
  <div class="top_nav_links">
    <ul>
      <li>
      <a  class="selected" href="<?php echo $this->url('application') ?>" ><?php echo $this->translate('Home') ?></a></li>
      <li><a  href="<?php echo $this->url('apply') ?>" ><?php echo $this->translate('Apply Passport/Visa') ?></a></li>
      <li><a  href="<?php echo $this->url('communicate',array('action' => 'feedback')) ?>" ><?php echo $this->translate('Feedback') ?></a></li>
      <li><a  href="<?php echo $this->url('communicate',array('action' => 'contactus')) ?>" ><?php echo $this->translate('Contact Us') ?></a></li>
      <li><a  href="<?php echo $this->url('info',array('action'=>'howtoapply')) ?>" ><?php echo $this->translate('How To Apply') ?></a></li>
      <li><a  href="<?php echo $this->url('knowyourstatus') ?>" ><?php echo $this->translate('Know Your Status') ?></a></li>
    </ul>
  </div>
</div>
<div class="clear"></div>
