<?php echo $this->doctype(); ?>
<html lang="en">

<?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

<head>
        <?php echo $this->headTitle($this->translate('Passport Services LLC'))->setSeparator(' - ')->setAutoEscape(false) ?>
        

        <!-- styles sheet -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/main.css')
                        ->prependStylesheet($this->basePath() . '/css/global.css');
         ?>

        <!-- Js Scripts -->
        <?php echo $this->headScript()
           // ->prependFile($this->basePath() . '/js/jquery-1.js')
            ->prependFile($this->basePath() . '/js/general.js')
            //->prependFile($this->basePath() .'/js/ckeditor/ckeditor.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js');
         ?>
  </head>
	    <body>
		     <div>
		       <?php echo $this->partial('layout/header'); ?>
		     </div>
				     <div>
				     <?php echo $this->content; ?>
				     </div>
		     <div>
		      <?php echo $this->partial('layout/footer'); ?>
		     </div>
	    </body>
</html>
    
    
    
    

