<div class="clear"></div>
<div class="wrapper">
	<div class="clear">&nbsp;</div>
	<!--Main Container Section Starts Here-->
	<div class="container_main">
		<div class="new_container">
			<!--Heading Container Section Starts Here-->
			<div class="heading_container">
				<div class="heading_container_left"></div>
				<div class="heading_containerbg">
					<div class="page_heading">Passport Form</div>
				</div>
				<div class="heading_container_right"></div>
			</div>
			<!--Heading Container Section Ends Here-->
			<!--Form Inner/Inside Section Starts Here-->
			<div class="form_inside_section">
				<div class="bodyContent">
					<div class="dlForm multiForm">
                    <?php
																				$form = $this->passportForm;
																				$form->prepare ();
																				$form->setAttribute ( 'action', $this->url ( 'savepassport' ) );
																				echo $this->form ()->openTag ( $form );
																				?>
            <div>
							<!--Fieldset Section Starts Here-->

							<fieldset class="bdr">
								<legend class=" formHead"> Application Information</legend>
								<dl>
									<dt>
										<label for="passport_application_title_id"><?php echo $this->formLabel($form->get('title')); ?></label>
									</dt>
									<dd>
                 <?php echo $this->formSelect($form->get('title')); ?>
                                  <br> <span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt><?php
											$name = $form->get ( 'first_name' );
											echo $this->formLabel()->openTag($name) . $name->getLabel();
											?>
											<span class="red">*</span>
											<?php $this->formLabel()->closeTag();
											?>
									</dt>
									<dd>
                  <?php echo $this->formInput($form->get('first_name')); ?>                 <br>
										<span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt>
										<?php echo $this->formLabel($form->get('last_name')); ?>
									</dt>
									<dd>
                  <?php echo $this->formInput($form->get('last_name')); ?> <br>
										<span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt>
										<?php echo $this->formLabel($form->get('gender')); ?>
									</dt>
									<dd><?php echo $this->formSelect($form->get('gender')); ?>
                                   <br> <span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt>
										<label for="passport_application_date_of_birth">Date of birth
											<span class="red">*</span>
										</label>
									</dt>
									<dd id="db_width">
										<select name="passport_application[date_of_birth][day]"
											id="passport_application_date_of_birth_day">
											<option value="" selected="selected"></option>
											<option value="1">01</option>
											<option value="2">02</option>
											<option value="3">03</option>
											<option value="4">04</option>
											<option value="5">05</option>
											<option value="6">06</option>
											<option value="7">07</option>
											<option value="8">08</option>
											<option value="9">09</option>
											<option value="10">10</option>
											<option value="11">11</option>
											<option value="12">12</option>
											<option value="13">13</option>
											<option value="14">14</option>
											<option value="15">15</option>
											<option value="16">16</option>
											<option value="17">17</option>
											<option value="18">18</option>
											<option value="19">19</option>
											<option value="20">20</option>
											<option value="21">21</option>
											<option value="22">22</option>
											<option value="23">23</option>
											<option value="24">24</option>
											<option value="25">25</option>
											<option value="26">26</option>
											<option value="27">27</option>
											<option value="28">28</option>
											<option value="29">29</option>
											<option value="30">30</option>
											<option value="31">31</option>
										</select>/<select
											name="passport_application[date_of_birth][month]"
											id="passport_application_date_of_birth_month">
											<option value="" selected="selected"></option>
											<option value="1">01</option>
											<option value="2">02</option>
											<option value="3">03</option>
											<option value="4">04</option>
											<option value="5">05</option>
											<option value="6">06</option>
											<option value="7">07</option>
											<option value="8">08</option>
											<option value="9">09</option>
											<option value="10">10</option>
											<option value="11">11</option>
											<option value="12">12</option>
										</select>/<select
											name="passport_application[date_of_birth][year]"
											id="passport_application_date_of_birth_year">
											<option value="" selected="selected"></option>
											<option value="1914">1914</option>
											<option value="1915">1915</option>
											<option value="1916">1916</option>
											<option value="1917">1917</option>
											<option value="1918">1918</option>
											<option value="1919">1919</option>
											<option value="1920">1920</option>
											<option value="1921">1921</option>
											<option value="1922">1922</option>
											<option value="1923">1923</option>
											<option value="1924">1924</option>
											<option value="1925">1925</option>
											<option value="1926">1926</option>
											<option value="1927">1927</option>
											<option value="1928">1928</option>
											<option value="1929">1929</option>
											<option value="1930">1930</option>
											<option value="1931">1931</option>
											<option value="1932">1932</option>
											<option value="1933">1933</option>
											<option value="1934">1934</option>
											<option value="1935">1935</option>
											<option value="1936">1936</option>
											<option value="1937">1937</option>
											<option value="1938">1938</option>
											<option value="1939">1939</option>
											<option value="1940">1940</option>
											<option value="1941">1941</option>
											<option value="1942">1942</option>
											<option value="1943">1943</option>
											<option value="1944">1944</option>
											<option value="1945">1945</option>
											<option value="1946">1946</option>
											<option value="1947">1947</option>
											<option value="1948">1948</option>
											<option value="1949">1949</option>
											<option value="1950">1950</option>
											<option value="1951">1951</option>
											<option value="1952">1952</option>
											<option value="1953">1953</option>
											<option value="1954">1954</option>
											<option value="1955">1955</option>
											<option value="1956">1956</option>
											<option value="1957">1957</option>
											<option value="1958">1958</option>
											<option value="1959">1959</option>
											<option value="1960">1960</option>
											<option value="1961">1961</option>
											<option value="1962">1962</option>
											<option value="1963">1963</option>
											<option value="1964">1964</option>
											<option value="1965">1965</option>
											<option value="1966">1966</option>
											<option value="1967">1967</option>
											<option value="1968">1968</option>
											<option value="1969">1969</option>
											<option value="1970">1970</option>
											<option value="1971">1971</option>
											<option value="1972">1972</option>
											<option value="1973">1973</option>
											<option value="1974">1974</option>
											<option value="1975">1975</option>
											<option value="1976">1976</option>
											<option value="1977">1977</option>
											<option value="1978">1978</option>
											<option value="1979">1979</option>
											<option value="1980">1980</option>
											<option value="1981">1981</option>
											<option value="1982">1982</option>
											<option value="1983">1983</option>
											<option value="1984">1984</option>
											<option value="1985">1985</option>
											<option value="1986">1986</option>
											<option value="1987">1987</option>
											<option value="1988">1988</option>
											<option value="1989">1989</option>
											<option value="1990">1990</option>
											<option value="1991">1991</option>
											<option value="1992">1992</option>
											<option value="1993">1993</option>
											<option value="1994">1994</option>
											<option value="1995">1995</option>
											<option value="1996">1996</option>
											<option value="1997">1997</option>
											<option value="1998">1998</option>
											<option value="1999">1999</option>
											<option value="2000">2000</option>
											<option value="2001">2001</option>
											<option value="2002">2002</option>
											<option value="2003">2003</option>
											<option value="2004">2004</option>
											<option value="2005">2005</option>
											<option value="2006">2006</option>
											<option value="2007">2007</option>
											<option value="2008">2008</option>
											<option value="2009">2009</option>
											<option value="2010">2010</option>
											<option value="2011">2011</option>
											<option value="2012">2012</option>
											<option value="2013">2013</option>
											<option value="2014">2014</option>
											<option value="2015">2015</option>
											<option value="2016">2016</option>
											<option value="2017">2017</option>
											<option value="2018">2018</option>
											<option value="2019">2019</option>
											<option value="2020">2020</option>
											<option value="2021">2021</option>
											<option value="2022">2022</option>
											<option value="2023">2023</option>
											<option value="2024">2024</option>
											<option value="2025">2025</option>
											<option value="2026">2026</option>
											<option value="2027">2027</option>
											<option value="2028">2028</option>
										</select><input size="10"
											id="passport_application_date_of_birth_date"
											disabled="disabled" type="hidden"><input
											id="passport_application_date_of_birth_button" value="..."
											class="calBtn" type="button">
										<script>
function wfd_passport_application_date_of_birth_update_linked(cal)
  { 
var p = cal.params;
    m = cal.date.getMonth()+1
    d = cal.date.getDate()
    y = cal.date.getFullYear();
   //console.log(cal);
     jQuery("#passport_application_date_of_birth_year").val(y);
    jQuery("#passport_application_date_of_birth_month").val(m);
    jQuery("#passport_application_date_of_birth_day").val(d);
    if(cal.dateClicked){p.inputField.value = cal.date.print(p.ifFormat);cal.callCloseHandler();}
  }

function wfd_passport_application_date_of_birth_update_from_linked_days(cal)
  {
toDay = new Date();
  //console.log(cal.dateFormat);
   y = $('#passport_application_date_of_birth_year').val();
   m = $('#passport_application_date_of_birth_month').val();
   d = $('#passport_application_date_of_birth_day').val();
   if(y==''){}
   if(m==''){m= toDay.getMonth()+1;}
   if(d==''){d=toDay.getDate();}
   $('#passport_application_date_of_birth_date').val(y+'/'+m+'/'+d);
  //console.log(cal);
  }

 Calendar.setup({
 inputField : "passport_application_date_of_birth_date",
 button : "passport_application_date_of_birth_button",
//onUpdate : wfd_passport_application_date_of_birth_update_from_linked_days,
onSelect : wfd_passport_application_date_of_birth_update_linked

 });
jQuery("#passport_application_date_of_birth_month, #passport_application_date_of_birth_day, #passport_application_date_of_birth_year").change(wfd_passport_application_date_of_birth_update_from_linked_days);
</script>
										<br> <span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt><?php
											$name = $form->get ( 'address1' );
											echo $this->formLabel()->openTag($name) . $name->getLabel();
											?>
											<span class="red">*</span>
											<?php $this->formLabel()->closeTag();
											?>
									</dt>
									<dd>
                  <?php echo $this->formInput($form->get('address1')); ?>                  <br>
										<span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt>
										<?php echo $this->formLabel($form->get('address2')); ?>
									</dt>
									<dd>
                  <?php echo $this->formInput($form->get('address2')); ?>                <br>
										<span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt><?php
											$name = $form->get ( 'email' );
											echo $this->formLabel()->openTag($name) . $name->getLabel();
											?>
											<span class="red">*</span>
											<?php $this->formLabel()->closeTag();
											?>
									
									</dt>
									<dd>
                  <?php echo $this->formInput($form->get('email')); ?>                 <br>
										<span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt><?php
											$name = $form->get ( 'state' );
											echo $this->formLabel()->openTag($name) . $name->getLabel();
											?>
											<span class="red">*</span>
											<?php $this->formLabel()->closeTag();
											?>
									</dt>
									<dd>
                  <?php echo $this->formInput($form->get('state')); ?>                  <br>
										<span class="error_msg"> </span>
									</dd>
								</dl>
								<dl>
									<dt>
										<?php echo $this->formLabel($form->get('country')); ?>
									</dt>
									<dd>
                   <?php echo $this->formSelect($form->get('country')); ?>             <br>
										<span class="error_msg"> </span>
									</dd>
								</dl>
							</fieldset>
							<!--input type="text" name="passport_application[processing_country_id]" value="BR" /-->
							<!--Fieldset Section Ends Here-->
							<!--Button Section Starts Here-->
							<div class="pixbr XY20">
								<center id="multiFormNav">
									<div align="center">
										<table class="nobrd" align="center">
											<tbody>
												<tr>
													<td align="center"><div class="lblButton">
                             <?php echo $this->formSubmit($form->get('submit')); ?>
                            </div>
														<div class="lblButtonRight">
															<div class="btnRtCorner"></div>
														</div></td>
													<td align="center"><div class="lblButton">
															<input value="Cancel" class="btnArea"
																onclick="history.go(-1)" type="button">
														</div>
														<div class="lblButtonRight">
															<div class="btnRtCorner"></div>
														</div></td>
												</tr>
											</tbody>
										</table>
									</div>
								</center>
							</div>
							<!--Button Section Ends Here-->
						</div>
           <?php echo $this->form()->closeTag(); ?>
           </div>
				</div>
			</div>
			<!--Form Inner/Inside Section Ends Here-->
		</div>
		<div class="container_bottombg"></div>
	</div>
	<!--Main Container Section Ends Here-->
</div>
<div class="clear"></div>