
<div class="clear"></div>
<div class="wrapper">
	<div class="clear">&nbsp;</div>
	<div class="container_main">
		<div class="new_container">
			<!--Heading Container Section Starts Here-->
			<div class="heading_container">
				<div class="heading_container_left"></div>
				<div class="heading_containerbg">
					<div class="page_heading">Payment Form</div>
				</div>
				<div class="heading_container_right"></div>
			</div>
			<div class="form_inside_section">
				<div class="bodyContent">
					<div class="redBigMessage" align="center">Due to regulations, we do
						not allow use of same card more than once in</div>
					
					<?php
    $form = $this->paymentForm;
    $form->prepare();
    echo $this->form()->openTag($form);
    $this->headLink()->appendStylesheet($this->basePath() . '/css/main.css');    
    
    ?>
					
						<table style="width: 100%; margin-bottom: 10px;" border="1">
						<tbody>
							<tr>

								<td><table style="margin: auto; vertical-align: top;"
										width="100%">
										<tbody>
											<tr>
												<td class="blbar" colspan="2" align="right"><p>Billing
														information</p></td>
											</tr>
											<tr>
												<td colspan="2" align="right"><p class="red">*Required
														Information</p></td>
											</tr>
											<tr>
												<td colspan="2" align="right"><p class="red">Please enter
														the exact billing address which is printed on your Credit
														Card statement</p></td>
											</tr>
											<tr>
												<td width="40%"><?php
            $name = $form->get('first_name');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('first_name')); ?>  <br>
													<div class="red" id="first_name_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('last_name');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('last_name')); ?>  <br>
													<div class="red" id="last_name_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('address1');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('address1')); ?>  <br>
													<div class="red" id="address1_error"></div></td>
											</tr>
											<tr>
												<td><?php echo $this->formlabel($form->get('address2')); ?></td>
												<td><?php echo $this->formInput($form->get('address2')); ?>  <br>
													<div class="red" id="address2_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('town');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('town')); ?>  <br>
													<div class="red" id="town_error"></div></td>
											</tr>
											<tr>
												<td><?php echo $this->formlabel($form->get('state')); ?></td>
												<td><?php echo $this->formInput($form->get('state')); ?>  <br>
													<div class="red" id="state_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('zip');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('zip')); ?> <br>
													<div class="red" id="zip_error"></div></td>
											</tr>
											<tr>
												<td><?php echo $this->formLabel($form->get('country')); ?></td>
												<td><?php echo $this->formSelect($form->get('country')); ?>  <br>
													<div class="red" id="country_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('email');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('email')); ?> <br>
													<div class="red" id="email_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('phone');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('phone')); ?>  <br>
													<div class="red" id="phone_error"></div></td>
											</tr>
										</tbody>
									</table> <br></td>
								<td style="width: 50%; vertical-align: top;">

									<table style="margin: auto; margin-bottom: 10px;" width="100%">
										<tbody>
											<tr>
												<td class="blbar" colspan="2" align="right"><p>Card
														information</p></td>
											</tr>
											<tr>
												<td><?php echo $this->formLabel($form->get('card_type')); ?></td>
												<td><?php echo $this->formSelect($form->get('card_type')); ?>  <br>
													<div class="red" id="card_type_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('card_number');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('card_number')); ?> <br>
													<div class="red" id="card_Num_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('card_holder');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('card_holder')); ?> <br>
													<div class="red" id="card_holder_error"></div></td>
											</tr>
											<tr>
												<td><label for="ep_gray_pay_request_expiry_date">Expiry Date</label><span
													class="red">*</span></td>
												<td><select name="ep_gray_pay_request[expiry_date][month]"
													id="ep_gray_pay_request_expiry_date_month">
														<option selected="selected" value="1">01</option>
														<option value="2">02</option>
														<option value="3">03</option>
														<option value="4">04</option>
														<option value="5">05</option>
														<option value="6">06</option>
														<option value="7">07</option>
														<option value="8">08</option>
														<option value="9">09</option>
														<option value="10">10</option>
														<option value="11">11</option>
														<option value="12">12</option>
												</select>-<select
													name="ep_gray_pay_request[expiry_date][year]"
													id="ep_gray_pay_request_expiry_date_year">
														<option selected="selected" value="2013">2013</option>
														<option value="2014">2014</option>
														<option value="2015">2015</option>
														<option value="2016">2016</option>
														<option value="2017">2017</option>
														<option value="2018">2018</option>
														<option value="2019">2019</option>
														<option value="2020">2020</option>
														<option value="2021">2021</option>
														<option value="2022">2022</option>
														<option value="2023">2023</option>
												</select> <br>
													<div class="red" id="expiry_date_error"></div></td>
											</tr>
											<tr>
												<td><?php
            $name = $form->get('cvv');
            echo $this->formLabel()->openTag($name) . $name->getLabel();
            ?>
											<span class="red">*</span>
											<?php
        
        $this->formLabel()->closeTag();
        ?></td>
												<td><?php echo $this->formInput($form->get('cvv')); ?> </div>
												</td>
											</tr>




										</tbody>
									</table>
								</td>
							</tr>
						</tbody>
						<tfoot>
							<tr>
								<td colspan="2">
									<div style="margin: auto; width: 100%;">
										<input name="ep_gray_pay_request[agreed]"
											id="ep_gray_pay_request_agreed" type="checkbox"> &nbsp; I
										agree to <a
											onclick="var w=window.open(this.href,'Window title','width=610,height=600,left=320,top=0,scrollbars=yes');w.focus();return false;"
											href="http://passportservicesllc.com/index.php/cms/termsAndConditions">Terms
											and Conditions</a>
									</div>
									<div class="red" id="error_agreedterm"></div>
								</td>
							</tr>
							<tr>
								<td colspan="2"><input name="orderNumber" id="orderNumber"
									value="13934726" type="hidden">
									<div id="payButDiv">
										<div class="lblButton">
											<input value="Make Payment" id="payBut" name="payBut"
												class="btnArea" type="submit">
										</div>
										<div class="lblButtonRight">
											<div class="btnRtCorner"></div>
										</div>
									</div>
									<div id="loader" align="center"></div></td>
							</tr>
						</tfoot>
					</table>
					<?php echo $this->form()->closeTag();?>
				</div>
			</div>
		</div>
	 <div class="container_bottombg"></div>
  </div>
  <!--Main Container Section Ends Here-->
</div>
<script>
    function validateForms(){
        var err  = 0;

        if($('#ep_gray_pay_request_first_name').val() == "")
        {
            $('#first_name_error').html("Please enter first name");
            err = err+1;
        }else if(validateString($('#ep_gray_pay_request_first_name').val()) !=0)
        {
            $('#first_name_error').html("Please enter valid first name");
            err = err+1;
        }
        else
        {
            $('#first_name_error').html("");
        }


        if($('#ep_gray_pay_request_last_name').val() == "")
        {
            $('#last_name_error').html("Please enter last name");
            err = err+1;
        }else if(validateString($('#ep_gray_pay_request_last_name').val()) !=0)
        {
            $('#last_name_error').html("Please enter valid last name");
            err = err+1;
        }
        else
        {
            $('#last_name_error').html("");
        }

        if($('#ep_gray_pay_request_address1').val() == "")
        {
            $('#address1_error').html("Please enter address1");
            err = err+1;
        }else if(validateString($('#ep_gray_pay_request_address1').val()) !=0)
        {
            $('#address1_error').html("Please enter valid address");
            err = err+1;
        }
        else
        {
            $('#address1_error').html("");
        }

        if( $('#ep_gray_pay_request_address2').val() != "" && validateString($('#ep_gray_pay_request_address2').val()) !=0)
        {
            $('#address2_error').html("Please enter valid address");
            err = err+1;
        }
        else
        {
            $('#address2_error').html("");
        }

        if($('#ep_gray_pay_request_town').val() == "")
        {
            $('#town_error').html("Please enter town");
            err = err+1;
        }else if(validateString($('#ep_gray_pay_request_town').val()) !=0)
        {
            $('#town_error').html("Please enter valid town");
            err = err+1;
        }
        else
        {
            $('#town_error').html("");
        }

        if( $('#ep_gray_pay_request_state').val() != "" && validateString($('#ep_gray_pay_request_state').val()) !=0)
        {
            $('#state_error').html("Please enter valid state");
            err = err+1;
        }
        else
        {
            $('#state_error').html("");
        }

        

        if($('#ep_gray_pay_request_country').val() == "")
        {
            $('#country_error').html("Please enter country");
            err = err+1;
        }
        else
        {
            $('#country_error').html("");
        }


        if($('#ep_gray_pay_request_email').val() == "")
        {
            $('#email_error').html("Please enter Email");
            err = err+1;
        }
        else if(validateEmail($('#ep_gray_pay_request_email').val()) !=0)
        {
            $('#email_error').html("Please enter Valid Email");
            err = err+1;
        }
        else
        {
            $('#email_error').html("");
        }


        if($('#ep_gray_pay_request_phone').val() == "")
        {
            $('#phone_error').html("Please enter Mobile number");
            err = err+1;
        }else if(validatePhone($('#ep_gray_pay_request_phone').val()) !=0)
        {
            $('#phone_error').html("Please enter Valid Mobile number");
            err = err+1;
        }
        else
        {
            $('#phone_error').html("");
        }
        if($('#ep_gray_pay_request_card_Num').val() == "")
        {
            $('#card_Num_error').html("Please enter card  number");
            err = err+1;
        }
        else if(nmiCheckCardType($('#ep_gray_pay_request_card_Num').val()) !=0){
            $("#card_Num_error").html('Please enter correct Card Number')
            err = err+1;
        }
        else
        {
            $('#card_Num_error').html("");
        }

        if($('#ep_gray_pay_request_card_holder').val() == "")
        {
            $('#card_holder_error').html("Please enter card holder name");
            err = err+1;
        }else if(validateString($('#ep_gray_pay_request_card_holder').val()) !=0)
        {
            $('#card_holder_error').html("Please enter valid card holder name");
            err = err+1;
        }
        else
        {
            $('#card_holder_error').html("");
        }

        if($('#ep_gray_pay_request_cvv').val() == "")
        {
            $('#cvv_error').html("Please enter cvv");
            err = err+1;
        }
        else
        {
            $('#cvv_error').html("");
        }

        if(!ValidateExpDate($('#ep_gray_pay_request_expiry_date_year').val(),$('#ep_gray_pay_request_expiry_date_month').val()))
        {
            $('#expiry_date_error').html("Invalid expiry date ");
            err = err+1;
        }
        else
        {
            $('#expiry_date_error').html("");
        }


        if($('#ep_gray_pay_request_agreed:checked').val() == null)
        {
            $('#error_agreedterm').html("Please agree to Terms & Conditions");
            err = err+1;
        }
        else
        {
            $('#error_agreedterm').html("");
        }
        if(err == 0)
        {
            return true;

        }else{
            $('#payBut').show();
            $('#loader').html('');
            return false;
        }


    }


    function validateString(str)
    {
        var reg = /^[A-Za-z0-9 \' \` \- \. \,]*$/; //allow special characters ` ' - . and space
        if(reg.test(str) == false) {
            return 1;
        }

        return 0;
    }
    function validateEmail(email) {

        var reg = /^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/;
        if(reg.test(email) == false) {

            return 1;
        }

        return 0;
    }

    function validatePhone(phoneNumber) {
        //      var reg = /^((\+)?(\d{2}[-]))?(\d{10}){1}?$/;
        //var reg = /^((\+)?(\d{2}))?(\d{10-15}){1}?$/;
        var reg = /^[0-9 [\]+()-]{8,20}?$/;
        if(reg.test(phoneNumber) == false) {
            return 1;
        }

        return 0;
    }
</script>


<div class="clear"></div>


