<div class="wrapper">
    <div class="clear">&nbsp;</div>
    <div class="container_main">
        <div class="new_container">
            <!--Heading Container Section Starts Here-->
            <div class="heading_container">
                <div class="heading_container_left"></div>
                <div class="heading_containerbg">
                    <div class="page_heading">How To Apply</div>
                </div>
                <div class="heading_container_right"></div>
            </div>
            <!--Heading Container Section Ends Here-->
            <!--Form Inner/Inside Section Starts Here-->
            <div class="form_inside_section">
                <div class="bodyContent">
                    <div class="body_text">
                        <p>Please follow the steps below to apply for and/or obtain your visa or passport:</p>
                        <p>Passport Services expedites the visa process for multiple countries by filing your visa or passport application electronically.  You then can pick it up at your visa or passport for your destination country at your destination country's local embassy nearest to your hometown.</p>
                        <p><strong>Step 1:</strong> Click on the "Apply Passport/Visa" link to get started with the application process.</p>
                        <p><strong>Step 2:</strong> Select the application type (Passport or Visa) and select your destination country.</p>
                        <p><strong>Step 3:</strong> Complete the electronic application and submit the form.</p>
                        <p><strong>Step 4:</strong> Pay the application processing fee on the checkout page.</p>
                        <p><strong>Step 5:</strong> Pick up your visa or passport at your destination country's local embassy closest to your hometown.</p>
                        <p>The process is complete.</p>
                        <p>**An email notification will be sent to your email confirming your status of transaction.</p>
                    </div>
                </div>
            </div>
            <!--Form Inner/Inside Section Ends Here-->
        </div>
        <div class="container_bottombg"></div>
    </div>
</div><div class="clear"></div>