<div class="wrapper">
  <div class="banner"><img alt="Passport Services" src="<?php $this->basepath('public')?>/images/banner.gif"></div>
 <?php
				if(isset($flashMessage) && !empty($flashMessage))
				{
					?>
					<div id="flash_notice" class="alertBox"> 
					<?php 
					foreach($flashMessage as $msg)
					{
						echo $msg;
					}
					?>
					</div>
					<?php 
				}
				
				
			?>
  <div class="container_main">
    <div class="new_container">
      <!--Heading Container Section Starts Here-->
      <div class="heading_container">
                <div class="heading_container_left"></div>
      
        <div class="heading_containerbg">
          <div class="page_heading">Welcome to Passport Services LLC</div>
        </div>
        <div class="heading_container_right"></div>
      </div>
      <!--Heading Container Section Ends Here-->
      <!--Form Inner/Inside Section Starts Here-->
      <div class="form_inside_section">
        <div class="bodyContent">
          <div class="introductory_content">
            <div class="passport_visa_img"><img alt="Passport Services" src="<?php $this->basepath('public')?>/images/passport_visa_img.gif"></div>
            
            
           
            
            
            <div class="intro_text">PassportservicesLLC provides you the
 most secure, easiest and fastest way to apply for passports and Visas 
for various Countries.
                You can pay application fee online using Visa/Master 
Cards in most secured and simplest way without any hassles.
                <div class="clear"><br></div><div class="body_text bg_highlight"><strong>Passport/Visas can be applied for Multiple Countries</strong></div>
            </div>
          </div>
          <div class="body_text"><strong>Now getting your Passport/Visa is as easy as <span class="fontsize_big">1 - 2 - 3</span></strong></div>
          <div class="clear"></div>
          <div class="process_first">
            <div class="process_top"></div>
            <div class="process_bg">
              <div class="step_name">STEP</div>
              <div class="steps">
                <div class="numbering">1</div>
              </div>
			  <div class="clear"></div>
			  <div class="process_name">Processing Country / Application Type</div>
			  <div class="clear"></div>
			  <div class="step_text">Click on "Apply Passport/Visa" and select for processing country and application type and proceed.</div>
            </div>
            <div class="process_bottom"></div>
          </div>
		  <div class="process_first">
            <div class="process_top"></div>
            <div class="process_bg">
              <div class="step_name">STEP</div>
              <div class="steps">
                <div class="numbering">2</div>
              </div>
			  <div class="clear"></div>
			  <div class="process_name">Personal Information Form</div>
			  <div class="clear"></div>
			  <div class="step_text">Fill in the required application information and submit.</div>
            </div>
            <div class="process_bottom"></div>
          </div>
		  <div class="process_first">
            <div class="process_top"></div>
            <div class="process_bg">
              <div class="step_name">STEP</div>
              <div class="steps">
                <div class="numbering">3</div>
              </div>
			  <div class="clear"></div>
			  <div class="process_name">Payment Details</div>
			  <div class="clear"></div>
			  <div class="step_text">Provide the payment details and make the payment. <strong>And you are done!</strong></div>
            </div>
            <div class="process_bottom"></div>
          </div>


        </div>
      </div>
      <!--Form Inner/Inside Section Ends Here-->
    </div>
    <div class="container_bottombg"></div>
  </div>
</div>

